on:
  push:
    branches: ["main"]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [16.x, 18.x]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "npm"
  #     - run: npm ci
  #     - run: npm run build --if-present

  # Cypress_e2e:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run Cypress tests
  #       uses: cypress-io/github-action@v3
  #       with:
  #         browser: chrome
  #         record: false
  #         config-file: cypress.config.ts
  #         headless: true

  Zap_Security_Report:
    runs-on: ubuntu-latest
    # needs: Cypress_e2e
    steps:
      - name: Await for Vercel deployment
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        with:
          token: ${ { secrets.GITHUB_TOKEN } }
          max_timeout: 120000
          check_interval: 15
          vercel_password: ${ { secrets.VERCEL_PASSWORD } }
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: https://labelgenius.vercel.app/
